[window]
# startup_mode = "Maximized"
decorations = "None"
[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Medium" }
bold = { family = "JetBrains Mono Nerd Font"}
italic = { family = "JetBrains Mono Nerd Font"}
bold_italic = { family = "JetBrains Mono Nerd Font"}
size = 10
